# Generated by Django 2.2.1 on 2019-06-01 14:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Greenhouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=6, unique=True)),
                ('weather', models.CharField(choices=[('ANDES', 'ANDES'), ('COAST', 'COAST')], default='', max_length=10)),
                ('temperature', models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(25)])),
                ('capacity', models.IntegerField(default=1000, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(2000)])),
                ('available', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10, unique=True)),
                ('value', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)])),
            ],
        ),
        migrations.CreateModel(
            name='Orchid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=6, unique=True)),
                ('preferred_weather', models.CharField(choices=[('ANDES', 'ANDES'), ('COAST', 'COAST')], default='', max_length=10)),
                ('number', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)])),
                ('min_temperature', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(25)])),
                ('max_temperature', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(25)])),
                ('original_days_in_andes', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('original_days_in_coast', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('current_days_in_andes', models.IntegerField(default=5)),
                ('current_days_in_coast', models.IntegerField(default=5)),
                ('state', models.CharField(default='NOT_ASSIGNED', max_length=20)),
                ('greenhouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orchids.Greenhouse')),
            ],
        ),
    ]
