# Generated by Django 2.2.1 on 2019-05-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenhouse',
            name='available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='greenhouse',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='greenhouse',
            name='weather',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='orchid',
            name='current_days_in_andes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orchid',
            name='current_days_in_coast',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orchid',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orchid',
            name='original_days_in_andes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orchid',
            name='original_days_in_coast',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orchid',
            name='weather',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='greenhouse',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='orchid',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
