# Generated by Django 2.2.1 on 2019-05-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchids', '0003_auto_20190529_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orchid',
            name='weather',
        ),
        migrations.AddField(
            model_name='orchid',
            name='preferred_weather',
            field=models.CharField(choices=[('andes', 'andes'), ('coast', 'coast')], default='', max_length=200),
        ),
    ]
