# Generated by Django 2.2.1 on 2019-05-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchids', '0004_auto_20190529_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orchid',
            name='current_days_in_andes',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='orchid',
            name='current_days_in_coast',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='orchid',
            name='max_temperature',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='orchid',
            name='min_temperature',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='orchid',
            name='name',
            field=models.CharField(default='put your name here', max_length=200),
        ),
        migrations.AlterField(
            model_name='orchid',
            name='number',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='orchid',
            name='original_days_in_andes',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='orchid',
            name='original_days_in_coast',
            field=models.IntegerField(default=5),
        ),
    ]
