# Generated by Django 2.2.1 on 2019-05-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orchids', '0005_auto_20190529_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenhouse',
            name='name',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='orchid',
            name='name',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
