# Generated by Django 2.2.1 on 2019-05-29 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orchids', '0006_auto_20190529_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orchid',
            name='greenhouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orchids.Greenhouse'),
        ),
    ]
