# Generated by Django 2.2.1 on 2019-05-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchids', '0007_auto_20190529_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orchid',
            name='name',
            field=models.CharField(default='put your name here', max_length=200, unique=True),
        ),
    ]
