# Generated by Django 2.2.1 on 2019-05-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchids', '0008_auto_20190530_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orchid',
            name='name',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
