# Generated by Django 2.2.1 on 2019-06-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchids', '0009_auto_20190530_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenhouse',
            name='capacity',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='greenhouse',
            name='temperature',
            field=models.IntegerField(default=15),
        ),
    ]
