# Generated by Django 2.2.1 on 2019-06-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchids', '0011_auto_20190601_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greenhouse',
            name='state',
        ),
        migrations.AddField(
            model_name='orchid',
            name='state',
            field=models.CharField(choices=[('NOT ASSIGNED', 'NOT ASSIGNED'), ('ASSIGNED', 'ASSIGNED'), ('SOLD', 'SOLD'), ('DESTROYED', 'DESTROYED')], default='NOT ASSIGNED', max_length=200),
        ),
    ]
