# Generated by Django 2.2.1 on 2019-06-01 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchids', '0012_auto_20190601_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenhouse',
            name='capacity',
            field=models.IntegerField(default=1000, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='greenhouse',
            name='name',
            field=models.CharField(default='', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='greenhouse',
            name='temperature',
            field=models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AlterField(
            model_name='greenhouse',
            name='weather',
            field=models.CharField(choices=[('ANDES', 'ANDES'), ('COAST', 'COAST')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='orchid',
            name='max_temperature',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AlterField(
            model_name='orchid',
            name='min_temperature',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AlterField(
            model_name='orchid',
            name='name',
            field=models.CharField(default='', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='orchid',
            name='number',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='orchid',
            name='original_days_in_andes',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='orchid',
            name='original_days_in_coast',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='orchid',
            name='preferred_weather',
            field=models.CharField(choices=[('ANDES', 'ANDES'), ('COAST', 'COAST')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='orchid',
            name='state',
            field=models.CharField(default='NOT_ASSIGNED', max_length=10),
        ),
    ]
