# Generated by Django 2.2.1 on 2019-06-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchids', '0013_auto_20190601_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orchid',
            name='state',
            field=models.CharField(default='NOT_ASSIGNED', max_length=20),
        ),
    ]
