# Generated by Django 2.2.1 on 2019-06-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchids', '0015_vars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vars',
            name='name',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
